### ISSUE TITLE
The color and fontsize of stationname

### ISSUE THREAD

**Issue by negoahz** [railmapgen/railmapgen.github.io#103]
Can you support setting the color and font size of the stationname? I want the site name color to be the same as the line color，And the 
size of stationname is too small, how can I adjust the font size?

**Comment by thekingofcity** [comment]
Hi, station names from the station are not expected to be changed except for the content. The names, along with the station icon, are a set of predefined styles or designs that mimic the official design and minimize the effort to create dozens of stations.

However, this does not mean you are forced to go only with this option. One possible solution is clearing the content of the station names and adding text nodes from miscellaneous nodes. Or wait another month for the master node where you could convert and use your own SVGs (from Adobe Ai or Canvas, etc) in the canvas :)
