### ISSUE TITLE
Can't Add External Line

### ISSUE THREAD

**Issue by VenusObjectCosmos** [railmapgen/railmapgen.github.io#111]
Hi! I used the Rail Map Generator and I wanted to create more lines. I clicked on the + button and I could select whether I could make a branch or an external line. I wanted to make an external line but I couldn't..? I clicked on the button multiple times and it doesn't work. It's like the button went on ghost mode or something. Please help!
![Uploading Screenshot 2024-08-07 at 20.32.04.png…]()

**Comment by thekingofcity** [comment]
Hi, please wait for the upload process to be completed before opening an issue.

For external lines, they are only available in Shanghai Metro style, and only support branches meet the following requirements.

* Starts from LEFTEND and ends at any station between the first and last station on the main line. (first and last station excluded)
* Starts from any station between the first and last station on the main line and ends at RIGHTEND. (first and last station excluded)

Branches start from any station and end at any station on the main line is NOT SUPPORTED right now.

Thanks for your understanding and feel free to reopen if this doesn't solve the problem :)
