### ISSUE TITLE
Updating the desktop app

### ISSUE THREAD

**Issue by jacksonvil-s** [railmapgen/railmapgen.github.io#125]
Is this a problem where my desktop app is still on 3.4.15 and not updated...

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/db2ead06-00bf-416f-b2be-05459b6ebcc0">

**HELP HOW DO I UPDATE THIS THING!!!!!!**

**Comment by thekingofcity** [comment]
Hi, thanks for your suggestion.

We do see the enhanced user experience with this feature, but with all core contributors busy with all other important stuff, this last resort solution does not have such a priority to work on. As a workaround, you may expect a monthly release schedule on the first day of each month.

Bests,
thekingofcity
