### ISSUE TITLE
aarch64 mac application won't run a intel mac

### ISSUE THREAD

**Issue by minecraft542** [railmapgen/railmapgen.github.io#142]
<img width="261" alt="Screenshot 2024-12-06 at 2 39 03 PM" src="https://github.com/user-attachments/assets/55c2bf9d-c6e3-4c38-aa65-24f7733476d3">

**Comment by thekingofcity** [comment]
Hi, Intel Mac should go with this link https://github.com/railmapgen/railmapgen.github.io/releases/download/tauri-20241202/railmapgen_24.12.2_x64.dmg
