### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by SeraRus** [railmapgen/railmapgen.github.io#143]
Create (Save) bottom doesn't work

**Comment by SeraRus** [comment]
<img width="1506" alt="螢幕截圖 2024-12-07 下午12 17 16" src="https://github.com/user-attachments/assets/41d3aa48-8979-44b3-b908-378ad46f61ae">

**Comment by SeraRus** [comment]
目前json文件大小960kb
點擊建立沒反應

**Comment by thekingofcity** [comment]
This is really weird. I'll look into this tomorrow ):

**Comment by thekingofcity** [comment]
![image](https://github.com/user-attachments/assets/2e5f667c-7ecf-4329-aab9-e67de4ce44c0)

嗨，我在本地尝试为您账号添加一个云存档，没有遇到任何问题。欢迎您登陆账号后检查 :)

如果您还遇到这个问题，或许可以切换浏览器为Chrome或Firefox？如仍存在，欢迎先按F12打开开发者工具，点击创建按钮后，再截取开发者工具中console和network两个标签页的内容 :)

**Comment by SeraRus** [comment]
我依然無法創建新存檔，且無法同步，這裡是截圖：
<img width="709" alt="螢幕截圖 2024-12-08 下午1 01 14" src="https://github.com/user-attachments/assets/3e751eda-2d1c-44bb-82d9-8e5d0182c936">
<img width="711" alt="螢幕截圖 2024-12-08 下午1 01 27" src="https://github.com/user-attachments/assets/c5f8532b-b32f-4be5-81b5-28852366dce8">

**Comment by thekingofcity** [comment]
嗨，我们大概知道问题所在了，您的作品在本地导出时，json档案的大小是？这可能达到服务器所设置的限制上限了 :(

**Comment by SeraRus** [comment]
目前是1.2MB，可以提高會員的上限嗎:(

**Comment by thekingofcity** [comment]
嗨，看起来这与设计之中的限制有差别，我们将尽快研究并修复。不过最近两周比较忙碌，可能要请您稍等一会儿了，作为补偿，我们发送了额外的兑换码到您的邮箱中，请注意查收 :)

**Comment by SeraRus** [comment]
Any CHANGE? :)

**Comment by SeraRus** [comment]
我試圖使用離線版本編輯，然而點擊下載按鈕後並無反應，然後我也保存不到雲端，我的修改正岌岌可危 :(

**Comment by thekingofcity** [comment]
嗨，实在抱歉，slack已经回您，明天会细看 :)

**Comment by thekingofcity** [comment]
嗨，此问题已被修复，感谢您的汇报！

**Comment by thekingofcity** [comment]
Add `client_max_body_size 5M;` in the nginx server block :)
