### ISSUE TITLE
创建存档时出现了问题

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/railmapgen.github.io#146]
![image](https://github.com/user-attachments/assets/c03f9dbd-ac1e-48b7-b287-400bd4833cdd)
如图

**Comment by hackerfyl** [comment]
文件大小是1.12MB

**Comment by thekingofcity** [comment]
嗨，看起来这与设计之中的限制有差别，我们将尽快研究并修复。不过最近两周比较忙碌，可能要请您稍等一会儿了，作为补偿，请回复您的邮箱，我们将发送额外的兑换码 :)

**Comment by thekingofcity** [comment]
已发送，请注意查收 :)

**Comment by thekingofcity** [comment]
嗨，您现在应该可以正确同步作品了 :)

**Comment by thekingofcity** [comment]
See #143
