### ISSUE TITLE
.org和.io的网站有时无法登录

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/railmapgen.github.io#153]
![image](https://github.com/user-attachments/assets/42b39ee5-f621-4a94-9c87-b1bc86f7b324)
如图，登录时显示Too many requests, please try again later.

**Comment by thekingofcity** [comment]
嗨，在 #146 修复后，您应该不会再遇到此问题。如果仍然遇到，欢迎重新打开此议题讨论 :)
