### ISSUE TITLE
Host fonts used by MTR style of RMG and RMP

### ISSUE THREAD

**Issue by wongchito** [railmapgen/railmapgen.github.io#52]

**Comment by thekingofcity** [comment]
That should help us only maintain one source. But how will local run work? Still a `server.proxy` in `vite.config.ts`?

**Comment by wongchito** [comment]
> That should help us only maintain one source. But how will local run work? Still a `server.proxy` in `vite.config.ts`?
> 
> 

The fonts can be sourced from local disk if installed locally.

**Comment by wongchito** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#examples
