### ISSUE TITLE
Enhancement : app component update 建议：电脑版添加组件更新按钮/将组件拆分出来以进行更新/其它

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/railmapgen.github.io#57]
这个问题的提出，主要原因是：
**学校限制github等访问，在线使用网页版极其不方便，卡顿且有时无法访问，只能下载（下载安装包都用了我5分钟！）
但是，如果用离线版，你们的离线电脑版每月1日更新版时有时会有一些问题（比如1月1号的就有偏移出错问题，已经上报），同时，每次更新都要重新下载安装包，比较麻烦，而且也没办法单独更新APP组件。这对于使用着来说极其不便。**
如果你们能够实现，或者可以让用户手动更新组件，那么这个问题也就解决了。
下面是几种可能的方式

1、是否可以考虑添加“组件更新”按钮在电脑版？
能否考虑添加APP组件更新按钮，同时设置“一键更新”选项
注意，我希望组件更新不是更新到该月1号的版本，而是与github上相同或最接近的版本。我知道这个软件在不断成长，每一个版本都有可能有大大小小的问题，但是如果实现这个功能，电脑端离线版起码可以保证总能更新到一个错误对制图影响相对较小的组件版本。
![屏幕截图 2024-01-01 163216](https://github.com/railmapgen/railmapgen.github.io/assets/146333201/ca6b8660-8cbf-413f-8ed1-03d8af799e54)
图一为添加更新键的大致效果图
![无标题](https://github.com/railmapgen/railmapgen.github.io/assets/146333201/09beeb3e-6003-452a-9ec6-d09fe11b897b)
图二为点击更新后弹出的窗口的大致样子，其中点击右侧update all 可以一键更新所有组件到最新版，而下面的文字则是点击哪个，哪个组件就进行更新。
当然，如果后续你们想要更进一步开发这一个功能的话，可以考虑在更新页面添加最新组件版本号和说明。

2、在1不能实现的情况下，能否考虑将组件文件拆分出来以便于用户自行进行文件替换更新
可以在启动程序的同一级添加“Component" 文件夹，内置多个子文件夹分别存放几个组件的文件，需要时即可上github下载代码替换文件，以达到更新目的。

3、在1、2都不能实现的情况下，针对我这种情况，你们有没有什么其他方式可以帮助我

**Comment by thekingofcity** [comment]
嗨，自动更新或许是个很有吸引力的功能，不过近期无法实现。这是由于：
1. 离线版并非主要维护之发行版，我们期望以最小精力维护一个可以供受防火墙干扰用户的发行版。
2. 所使用的打包工具并不提供如此细粒度的更新，即要么不更新要么更新整个程序。
3. 目前项目的引用方式不允许单独升级某个组件，这是由于共同依赖了一个底层组件，不同版本混用可能造成兼容性问题。

对于离线版下载过慢的问题，网页加载时所提供的离线包下载链接是可以加速中国大陆地区用户的特定链接。只需要在下载链接前添加`https://mirror.ghproxy.com/`即可。例如去年底的版本下载链接为：https://mirror.ghproxy.com/https://github.com/railmapgen/railmapgen.github.io/releases/download/tauri-20240101/railmapgen_24.1.1_x64-setup.exe

另外对于部分增量更新，使用浏览器直接访问在线版反而是最好的解决方案。这是由于浏览器本身就实现了一套缓存机制。如果您之前成功加载过一个版本A，那么对于新版本B，只会有修改的程序文件和资源会被重新加载，在版本A中已经存在且未被修改过的代码或字体等将不会再次加载。与其单独在离线版中实现如此复杂增量更新机制，不如直接使用浏览器这一已经实现的工具会更好 :)

**Comment by CatAlan1028** [comment]
哎，这就是国防七子学校学生的苦，看来只能用手机热点了
![56898ed750a8465d7d1efca596d97080c63b8f26 png@100w_100h](https://github.com/railmapgen/railmapgen.github.io/assets/146333201/055b0f08-2b54-4ae5-8825-345be411645c)

**Comment by thekingofcity** [comment]
啊原来是10043呀，那还真是可惜，不如化悲愤为力量不管是推动北邮名产品防火墙的升级亦或是国内对于无需实名审查的进步如何？

**Comment by CatAlan1028** [comment]
呃，我HITSZ机器人专业的
