### ISSUE TITLE
Cannot download from offline app on mac

### ISSUE THREAD

**Issue by jacksonvil-s** [railmapgen/railmapgen.github.io#83]
I tried so many times and no matter what I can't download all my work on my mac and it's really frustrating how I can't save my work. It works fine on browser though, but I can't transfer onto it. (video linked)

[Screen Recording 2024-02-26 at 9.27.23 PM.zip](https://github.com/railmapgen/railmapgen.github.io/files/14405268/Screen.Recording.2024-02-26.at.9.27.23.PM.zip)

**Comment by thekingofcity** [comment]
Hi, this is a known issue. See #40 :)
