### ISSUE TITLE
现在RMP工具包更新后好像有些问题？

### ISSUE THREAD

**Issue by Hutk2023** [railmapgen/railmapgen.github.io#89]
加载完后，通常是这样些情况？
这是正常的版本号还是盗版的？
这是真的exe文件吗？

**Comment by wongchito** [comment]
Hi @Hutk2023 ,

該版本與現行GitHub鏡像版本一致，可放心使用。

我們最近的一個變更使版本號出現異常，我們現已修正該錯誤，但離線版本將於下月1號才會更新。

感謝閣下的查詢！
